language: python
python:
  - "3.7"
install:
  python -m pip install --upgrade pip
# command to run tests
script:
  - python -m  unittest discover -s  Tests

branches:
  only:
    - master
    - development
